name: Build - Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      id: prepare
      run: |
        echo "::set-output name=name::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
        echo "::set-output name=prefix::$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER-"
        echo "::set-output name=suffix::${GITHUB_REF#refs/*/}"

    - id: branch
      run: |
        if [[ "${{ github.ref }}" != "refs/tags/"* ]]; then
          BRANCH_BASE=$(printf "%q" "${{ github.base_ref }}")
          BRANCH_BASE=${BRANCH_BASE/refs\/heads\//}
          BRANCH_BASE=${BRANCH_BASE//\/\/-}
          BRANCH_COMPARE=$(printf "%q" "${{ github.head_ref }}")
          BRANCH_COMPARE=${BRANCH_COMPARE/refs\/heads\//}
          BRANCH_COMPARE=${BRANCH_COMPARE//\/\/-}
          BRANCH_REF=$(printf "%q" "${{ github.ref }}")
          BRANCH_PULL_REQUEST=${BRANCH_REF/refs\/pull\//}
          BRANCH_PULL_REQUEST=${BRANCH_PULL_REQUEST/refs\/heads\//}
          BRANCH_PULL_REQUEST=${BRANCH_PULL_REQUEST//\/\/-}
          VERSION_SUFFIX=merge-${BRANCH_BASE}-${BRANCH_COMPARE}
          echo "::set-output name=branch_base::$(eval printf "%s" "$BRANCH_BASE")"
          echo "::set-output name=branch_compare::$(eval printf "%s" "$BRANCH_COMPARE")"
          echo "::set-output name=branch_pull_request::$(eval printf "%s" "$BRANCH_PULL_REQUEST")"
          echo "::set-output name=version_suffix::$(eval printf "%s" "$VERSION_SUFFIX")"
        fi
      shell: bash
    - id: current_branch
      run: |
        if [[ "${{ github.ref }}" != "refs/tags/"* ]]; then
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "::set-output name=current_branch::${{ steps.branch.outputs.head_ref_branch }}"
          else
            echo "::set-output name=current_branch::${{ steps.branch.outputs.ref_branch }}"
          fi
        else
          REF=$(printf "%q" "${{ github.ref }}")
          REF_BRANCH=${REF/refs\/tags\/${{ inputs.strip_tag_prefix }}/}
          echo "::set-output name=current_branch::$(eval printf "%s" "$REF_BRANCH")"
        fi
      shell: bash

    - name: Debug
      run: echo ${{ steps.prepare.outputs.name }} - ${{ steps.prepare.outputs.prefix }} - ${{ steps.prepare.outputs.suffix }}

    - name: DebugTwo
      run: echo merge-${{ steps.branch.outputs.branch_base }}-${{ steps.branch.outputs.branch_pull_request }}

    - name: DebugTwoOne
      run: echo ${{ steps.branch.outputs.version_suffix }} ${{ steps.branch.outputs.version_suffix }}

    - name: DebugThree
      run: echo ${{ steps.current_branch.outputs.current_branch }} - ${{ steps.branch.outputs.ref_branch }}
