name: Build - Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - id: prepare
      run: |
        echo "::set-output name=name::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
        echo "::set-output name=version_prefix::$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER"

        BRANCH_BASE=${GITHUB_BASE_REF#refs/*/}
        BRANCH_BASE=${BRANCH_BASE//\//-}

        BRANCH_COMPARE=${GITHUB_HEAD_REF#refs/*/}
        BRANCH_COMPARE=${BRANCH_COMPARE//\//-}

        BRANCH_PULL_REQUEST=${GITHUB_REF#refs/*/}
        BRANCH_PULL_REQUEST=${BRANCH_PULL_REQUEST//\//-}

        VERSION_SUFFIX=merge-${BRANCH_BASE}-${BRANCH_COMPARE}

        echo "::set-output name=branch_base::$(eval printf "%s" "$BRANCH_BASE")"
        echo "::set-output name=branch_compare::$(eval printf "%s" "$BRANCH_COMPARE")"
        echo "::set-output name=branch_pull_request::$(eval printf "%s" "$BRANCH_PULL_REQUEST")"
        echo "::set-output name=version_suffix::$(eval printf "%s" "$VERSION_SUFFIX")"
      shell: bash

    - name: Debug
      run: echo ${{ steps.prepare.outputs.name }} - ${{ steps.prepare.outputs.version_prefix }}

    - name: DebugTwo
      run: echo merge-${{ steps.prepare.outputs.branch_base }}-${{ steps.prepare.outputs.branch_compare }} vs ${{ steps.branch.outputs.version_suffix }}

    - name: DebugTwoOne
      run: echo ${{ steps.prepare.outputs.branch_pull_request }}
