name: Build - Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      id: prepare
      run: |
        BRANCH_CURRENT=${GITHUB_REF#refs/*/}
        BRANCH_CURRENT=${BRANCH_CURRENT//\//-}

        echo "::set-output name=name::$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')"
        echo "::set-output name=version_prefix::$(date +'%Y.%m.%d').${GITHUB_RUN_NUMBER}"
        echo "::set-output name=branch_current::$(eval printf "%s" "$BRANCH_CURRENT")"

        if [[ ${GITHUB_EVENT_NAME} == 'pull_request' ]]; then
          BRANCH_BASE=${GITHUB_BASE_REF#refs/*/}
          BRANCH_BASE=${BRANCH_BASE//\//-}
          BRANCH_COMPARE=${GITHUB_HEAD_REF#refs/*/}
          BRANCH_COMPARE=${BRANCH_COMPARE//\//-}
          VERSION_SUFFIX="merge-${BRANCH_BASE}-${BRANCH_COMPARE}"

          echo "::set-output name=version_suffix::$(eval printf "%s" "$VERSION_SUFFIX")"
          echo "::set-output name=branch_base::$(eval printf "%s" "$BRANCH_BASE")"
          echo "::set-output name=branch_compare::$(eval printf "%s" "$BRANCH_COMPARE")"
        fi
      shell: bash

    - name: TEST
      run: echo ${{ github.event.repository.default_branch }}

    - name: Name
      run: echo ${{ steps.prepare.outputs.name }}

    - name: Prefix
      run: echo ${{ steps.prepare.outputs.version_prefix }}

    - name: Suffix
      run: echo ${{ steps.prepare.outputs.version_suffix }}

    - name: Branches
      if: ${{ steps.perpare.outputs.version_suffix == '' }}
      run: |
        echo Base:${{ steps.prepare.outputs.branch_base }}
        echo Compare:${{ steps.prepare.outputs.branch_compare }}
        echo Pull Request:${{ steps.prepare.outputs.branch_pull_request }}
