name: Build - Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      id: prepare
      run: |
        BRANCH_CURRENT=${GITHUB_REF#refs/*/}
        BRANCH_CURRENT=${BRANCH_CURRENT//\//-}


        if [[ ${GITHUB_EVENT_NAME} == 'pull_request' ]]; then
          BRANCH_BASE=${GITHUB_BASE_REF#refs/*/}
          BRANCH_BASE=${BRANCH_BASE//\//-}
          BRANCH_COMPARE=${GITHUB_HEAD_REF#refs/*/}
          BRANCH_COMPARE=${BRANCH_COMPARE//\//-}
          VERSION_SUFFIX="-merge-${BRANCH_BASE}-${BRANCH_COMPARE}"
        elif [[ ${GITHUB_EVENT_NAME} == ${{ github.event.repository.default_branch }} ]]; then
          VERSION_SUFFIX="-${BRANCH_CURRENT}"
        fi

        echo "::set-output name=name::$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')"
        echo "::set-output name=version_prefix::$(date +'%Y.%m.%d').${GITHUB_RUN_NUMBER}"
        echo "::set-output name=version_suffix::$(eval printf "%s" "$VERSION_SUFFIX")"
        echo "::set-output name=branch::$(eval printf "%s" "$BRANCH_CURRENT")"
      shell: bash

    - name: Outputs
      run: |
        echo ${{ steps.prepare.outputs.name }}
        echo ${{ steps.prepare.outputs.version_prefix }}
        echo ${{ steps.prepare.outputs.version_suffix }}

    - name: Branches
      if: ${{ steps.perpare.outputs.branch == github.event.repository.default_branch }}
      run: |
        echo Base:${{ steps.prepare.outputs.branch_base }}
        echo Compare:${{ steps.prepare.outputs.branch_compare }}
        echo Current:${{ steps.prepare.outputs.branch_current }}
